config/routes.rb
TermProject::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  root 'welcome#index'

  get 'stations/search(.:format)' => 'stations#search'

  resources :stations, :prices, :fuel_types, :station_fuel_types, :cities, :zip_codes

end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :station_fuel_types, dependent: :destroy
  has_many :prices, through: :station_fuel_types
  has_many :fuel_types, through: :station_fuel_types

  validates :name, presence: true, length: { minimum: 3 }
  validates :address, :city, :state, :country, presence: true, if: "lat.nil? or lon.nil?"
  #validates :lat, :lon, presence: true, if: "address.nil? or city.nil? or state.nil? or country.nil?"

  geocoded_by :street_address, :latitude  => :lat, :longitude => :lon
  after_validation :geocode

  def prices
    prices = Array.new(4)

    station_fuel_types.each { |sft|
      #logger.debug "Station Fuel Type #{sft.id} present with price $#{sft.price.price}"
      prices[sft.fuel_type_id-1] = '%.2f' % sft.price.price
    }

    return prices
  end

  def street_address
    [address, city, state, country].compact.join(', ')
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def create
    @station = Station.new(station_params)
    
    if @station.save
      redirect_to @station
    else
      render 'new'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    redirect_to stations_path
  end

  def edit
    @station = Station.find(params[:id])
  end

  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def search
    ftid = params[:gas_type]
    @location = params[:search]
    distance = params[:distance]
    @miles = distance
    max_results = params[:max_results]

    if (@location == "")
      @location = "San Francisco"
    end

    #@price_87 = Hash.new
    #@price_89 = Hash.new
    #@price_91 = Hash.new
    #@price_diesel = Hash.new
    #@stations_with_all_prices = Station.joins(:station_fuel_types).where('station_fuel_types.fuel_type_id = 1 OR station_fuel_types.fuel_type_id = 2 OR station_fuel_types.fuel_type_id = 3 OR station_fuel_types.fuel_type_id = 4').near(@location, distance)
    #@stations_with_all_prices.each_with_index do |station, i|
      #if(sft = station.station_fuel_types.find_by(fuel_type_id: '1'))
        #@price_87[station.id] = '%.2f' % sft.price.price
      #end
      #if(sft = station.station_fuel_types.find_by(fuel_type_id: '2'))
        #@price_89[station.id] = '%.2f' % sft.price.price
      #end
      #if(sft = station.station_fuel_types.find_by(fuel_type_id: '3'))
        #@price_91[station.id] = '%.2f' % sft.price.price
      #end
      #if(sft = station.station_fuel_types.find_by(fuel_type_id: '4'))
        #@price_diesel[station.id] = '%.2f' % sft.price.price
      #end
    #end

    @stations = Station.joins(:station_fuel_types).where('station_fuel_types.fuel_type_id' => ftid).near(@location, distance).limit(max_results)
    @fuel_type = FuelType.find(ftid)

    @hash = Gmaps4rails.build_markers(@stations) do |station, marker|
      sft = station.station_fuel_types.find_by(fuel_type_id: ftid)
      #logger.debug sft.price.price
      price = '%.2f' % sft.price.price

      prices = station.prices
      @regular = prices[0]
      @mid = prices[1]
      @premium = prices[2]
      @diesel = prices[3]

      marker.lat station.lat
      marker.lng station.lon
      marker.title station.name
      marker.infowindow "<strong>#{station.name}</strong><br>#{station.address}" +
      "<table id='infowindow_table'>
      <tr>
      <th>Regular</th>
      <th>Mid-Grade</th>
      <th>Premium</th>
      <th>Diesel</th>
      </tr>
      <tr>
      <td>$#{@regular}</td>
      <td>$#{@mid}</td>
      <td>$#{@premium}</td>
      <td>$#{@diesel}</td>
      </tr>
      </table>"
      marker.json({ :name => station.name, :address => station.street_address, :price => price, :id => station.id})
    end
  end

  def show
    @station = Station.find(params[:id])

    @hash = Gmaps4rails.build_markers(@station) do |station, marker|
      prices = station.prices
      @regular = prices[0]
      @mid = prices[1]
      @premium = prices[2]
      @diesel = prices[3]

      marker.lat station.lat
      marker.lng station.lon
      marker.title station.name
      marker.infowindow "<strong>#{station.name}</strong><br>"
      marker.json({ :name => station.name, :address => station.street_address, :id => station.id})
    end
  end

  def update
    @station = Station.find(params[:id])

    if @station.update(params[:station].permit(:name, :company, :address, :city, :zip, :state, :country, :url, :phone, :email, :lat, :lon))
      redirect_to @station
    else
      render 'edit'
    end
  end

  private
  def is_number?(search_string)
    return search_string.to_i.to_s == search_string
  end

  def station_params
    params.require(:station).permit(:name, :company, :address, :city, :zip, :state, :country, :url, :phone, :email, :lat, :lon)
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for @station do |f| %>
  <% if @station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@station.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @station.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>
 
  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p>

  <p>
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Gas Station</h1>

<%= form_for :station, url: station_path(@station), method: :patch do |f| %>
  <% if @station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@station.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @station.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p>

  <p>
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing Gas Stations</h1>

<%= link_to 'New Station', new_station_path %> 
<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Company</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip Code</th>
    <th>Country</th>
    <th>Web Site</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @stations.each do |station| %>
    <tr>
      <td><%= station.id %></td>
      <td><%= station.name %></td>
      <td><%= station.company %></td>
      <td><%= station.address %></td>
      <td><%= station.city %></td>
      <td><%= station.state %></td>
      <td><%= station.zip %></td>
      <td><%= station.country %></td>
      <td><%= station.url %></td>
      <td><%= station.phone %></td>
      <td><%= station.email %></td>
      <td><%= station.lat %></td>
      <td><%= station.lon %></td>
      <td><%= link_to 'Show', station %></td>
      <td><%= link_to 'Edit', edit_station_path(station) %></td>
      <td><%= link_to 'Destroy', station_path(station),
                       method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br />

<%= link_to 'Back', controller: "welcome" %>

app/views/stations/new.html.erb
<h1>New Gas Station</h1>

<%= form_for :station, url: stations_path do |f| %>
  <% if @station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@station.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @station.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p>

  <p>
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', stations_path %>

app/views/stations/search.html.erb
<% content_for :content do %>
<h5>
    Showing <%= "#{@stations.length}" %> stations within <strong><%= "#{@miles}" %></strong> miles of 
    <strong><%= "#{@location}"%></strong><br>
    with fuel type <strong><%= @fuel_type.name  %></strong>, sorted by distance
</h5>
<% if (!@stations.blank?) %>
<table id="map_sidebar" style="width=100%;">
    <tr>
        <th>Station Name</th>
        <th>Gas Price</th>
    </tr>
</table>
<% else %>
<p>
    None found.
</p>
<% end %>
<% end %>

<% content_for :map do %>
<div id="map">
</div>
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<script>

var mapStyle =[
{
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#193341"
    }
    ]
},
{
    "featureType": "landscape",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#2c5a71"
    }
    ]
},
{
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#29768a"
    },
    {
        "lightness": -37
    }
    ]
},
{
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#406d80"
    }
    ]
},
{
    "featureType": "transit",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#406d80"
    }
    ]
},
{
    "elementType": "labels.text.stroke",
    "stylers": [
    {
        "visibility": "on"
    },
    {
        "color": "#3e606f"
    },
    {
        "weight": 2
    },
    {
        "gamma": 0.84
    }
    ]
},
{
    "elementType": "labels.text.fill",
    "stylers": [
    {
        "color": "#ffffff"
    }
    ]
},
{
    "featureType": "administrative",
    "elementType": "geometry",
    "stylers": [
    {
        "weight": 0.6
    },
    {
        "color": "#1a3541"
    }
    ]
},
{
    "elementType": "labels.icon",
    "stylers": [
    {
        "visibility": "off"
    }
    ]
},
{
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#2c5a71"
    }
    ]
}
];

function createSidebarLi(json){
    return (
        "<tr><td><li><a href='/stations/" + json.id + "'>" + json.name + "</a></li></td>" +
        "<td>$" + json.price + "</td></tr>");
  //return ("<li><a href='#'>" + json.name + "</a></li>");
};

function bindLiToMarker($li, marker){
  $li.on('mouseover', function(){
    google.maps.event.trigger(marker.getServiceObject(), 'click');
})
};

function createSidebar(json_array){
    _.each(json_array, function(json){
        var $li = $( createSidebarLi(json) );
        $li.appendTo('#map_sidebar');
        bindLiToMarker($li, json.marker);
    });
};

handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles :mapStyle}, internal: {id: 'map'}}, function(){
  var json_array = <%=raw @hash.to_json %>;

  var markers = handler.addMarkers(json_array);

  _.each(json_array, function(json, index){
    json.marker = markers[index];
});

  createSidebar(json_array);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<% end %>

<% content_for :crud do %>
<%= link_to "Gas Station List<br>".html_safe, controller: "stations" %>
<%= link_to "Fuel Type List<br>".html_safe, controller: "fuel_types" %>
<%= link_to "Prices List<br>".html_safe, controller: "prices" %>
<%= link_to "Cities List<br>".html_safe, controller: "cities" %>
<%= link_to "Zip Codes List<br>".html_safe, controller: "zip_codes" %>
<%= link_to "Station Fuel Type Map<br>".html_safe, controller: "station_fuel_types" %>
<% end %>

app/views/stations/show.html.erb
<% content_for :map do %>
<div id="map">
</div>
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<script>

var mapStyle =[
{
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#193341"
    }
    ]
},
{
    "featureType": "landscape",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#2c5a71"
    }
    ]
},
{
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#29768a"
    },
    {
        "lightness": -37
    }
    ]
},
{
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#406d80"
    }
    ]
},
{
    "featureType": "transit",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#406d80"
    }
    ]
},
{
    "elementType": "labels.text.stroke",
    "stylers": [
    {
        "visibility": "on"
    },
    {
        "color": "#3e606f"
    },
    {
        "weight": 2
    },
    {
        "gamma": 0.84
    }
    ]
},
{
    "elementType": "labels.text.fill",
    "stylers": [
    {
        "color": "#ffffff"
    }
    ]
},
{
    "featureType": "administrative",
    "elementType": "geometry",
    "stylers": [
    {
        "weight": 0.6
    },
    {
        "color": "#1a3541"
    }
    ]
},
{
    "elementType": "labels.icon",
    "stylers": [
    {
        "visibility": "off"
    }
    ]
},
{
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
    {
        "color": "#2c5a71"
    }
    ]
}
];

handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles :mapStyle}, internal: {id: 'map'}}, function(){
  var json_array = <%=raw @hash.to_json %>;

  var markers = handler.addMarkers(json_array);

  _.each(json_array, function(json, index){
    json.marker = markers[index];
});

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});
</script>

<% end %>


<% content_for :content do %>
<p>
  <strong><h5><%= @station.name %></h5></strong>
  <%= @station.address %>
  <br>
  <%= @station.city %>, <%= @station.state %>
  <br>
  <%= @station.zip %>
  <br>
  <%= @station.country %>
</p>

<p>
  <table style="min-width: 100%;">
    <tr>
      <th>87 Octane</th>
      <th>89 Octane</th>
      <th>91 Octane</th>
      <th>Diesel</th>
    </tr>
    <tr>
      <td>$<%= @regular %></td>
      <td>$<%= @mid %></td>
      <td>$<%= @premium %></td>
      <td>$<%= @diesel %></td>
    </tr>
  </table>
</p>

<p>
  <strong>Web Site:</strong>
  <%= @station.url %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @station.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @station.email %>
</p>

<%= link_to 'Back', stations_path %>
<%= link_to 'Edit', edit_station_path(@station) %>

<% end %>