config/routes.rb
TermProject::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  root 'welcome#index'

  get 'stations/search(.:format)' => 'stations#search'

  resources :stations, :prices, :fuel_types, :station_fuel_types, :cities, :zip_codes

end

app/models/zip_code.rb
class ZipCode < ActiveRecord::Base
end

app/controllers/zip_codes_controller.rb
class ZipCodesController < ApplicationController
  def create
    @zip_code = ZipCode.new(zip_code_params)
    @zip_code.save
    redirect_to @zip_code
  end

  def destroy
    @zip_code = ZipCode.find(params[:id])
    @zip_code.destroy

    redirect_to zip_codes_path
  end

  def edit
    @zip_code = ZipCode.find(params[:id])
  end

  def index
    @zip_codes = ZipCode.all
  end

  def new
  end

  def show
    @zip_code = ZipCode.find(params[:id])
  end

  def update
    @zip_code = ZipCode.find(params[:id])

    if @zip_code.update(params[:zip_code].permit(:zip_code, :lat, :lon))
      redirect_to @zip_code
    else
      render 'edit'
    end
  end

  private
    def zip_code_params
      params.require(:zip_code).permit(:zip_code, :lat, :lon)
    end
end

app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

app/views/zip_codes/edit.html.erb
<h1>Editing Zip Code</h1>
 
<%= form_for :zip_code, url: zip_code_path(@zip_code), method: :patch do |f| %>
  <% if @zip_code.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@zip_code.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @zip_code.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </p>
 
  <p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p>
 
  <p>
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', zip_codes_path %>

app/views/zip_codes/index.html.erb
<h1>Listing Zip Codes</h1>

<%= link_to 'New Zip Code', new_zip_code_path %> 
<table border="1">
  <tr>
    <th>Zip Code</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @zip_codes.each do |zip_code| %>
    <tr>
      <td><%= zip_code.zip_code %></td>
      <td><%= zip_code.lat %></td>
      <td><%= zip_code.lon %></td>
      <td><%= link_to 'Show', zip_code %></td>
      <td><%= link_to 'Edit', edit_zip_code_path(zip_code) %></td>
      <td><%= link_to 'Destroy', zip_code_path(zip_code),
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'Back', controller: "welcome" %>

app/views/zip_codes/new.html.erb
<h1>New Zip Code</h1>

<%= form_for :zip_code, url: zip_codes_path do |f| %>
  <p>
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </p>
 
  <p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p>
 
  <p>
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', zip_codes_path %>

app/views/zip_codes/show.html.erb
<p>
  <strong>Zip Code:</strong>
  <%= @zip_code.zip_code %>
</p>
 
<p>
  <strong>Latitude:</strong>
  <%= @zip_code.lat %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @zip_code.lon %>
</p>

<%= link_to 'Back', zip_codes_path %>