config/routes.rb
TermProject::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  root 'welcome#index'

  get 'stations/search(.:format)' => 'stations#search'

  resources :stations, :prices, :fuel_types, :station_fuel_types, :cities, :zip_codes

end

app/controllers/fuel_types_controller.rb
class FuelTypesController < ApplicationController
  def create
    @fuel_type = FuelType.new(fuel_type_params)
    
    if @fuel_type.save
      redirect_to @fuel_type
    else
      render 'new'
    end
  end

  def destroy
    @fuel_type = FuelType.find(params[:id])
    @fuel_type.destroy

    redirect_to fuel_types_path
  end

  def edit
    @fuel_type = FuelType.find(params[:id])
  end

  def index
    @fuel_types = FuelType.all
  end

  def new
    @fuel_type = FuelType.new
  end

  def show
    @fuel_type = FuelType.find(params[:id])
  end

  def update
    @fuel_type = FuelType.find(params[:id])

    if @fuel_type.update(params[:fuel_type].permit(:name, :description, :url))
      redirect_to @fuel_type
    else
      render 'edit'
    end
  end

  private
    def fuel_type_params
      params.require(:fuel_type).permit(:name, :description, :url)
    end
end

app/helpers/fuel_types_helper.rb
module FuelTypesHelper
end

app/views/fuel_types/edit.html.erb
<h1>Editing Fuel Type</h1>
 
<%= form_for :fuel_type, url: fuel_type_path(@fuel_type), method: :patch do |f| %>
  <% if @fuel_type.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@fuel_type.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @fuel_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', fuel_type_path %>

app/views/fuel_types/index.html.erb
<h1>Listing Fuel Types</h1>
 
<%= link_to 'New Fuel Type', new_fuel_type_path %>
<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
    <th>URL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @fuel_types.each do |fuel_type| %>
    <tr>
      <td><%= fuel_type.id %></td>
      <td><%= fuel_type.name %></td>
      <td><%= fuel_type.description %></td>
      <td><%= fuel_type.url %></td>
      <td><%= link_to 'Show', fuel_type %></td>
      <td><%= link_to 'Edit', edit_fuel_type_path(fuel_type) %></td>
      <td><%= link_to 'Destroy', fuel_type_path(fuel_type),
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br />

<%= link_to 'Back', controller: "welcome" %>

app/views/fuel_types/new.html.erb
<h1>New Fuel Type</h1>

<%= form_for :fuel_type, url: fuel_types_path do |f| %>
  <% if @fuel_type.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@fuel_type.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @fuel_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', fuel_types_path %>

app/views/fuel_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @fuel_type.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @fuel_type.description %>
</p>

<p>
  <strong>More Information Can Be Found At:</strong>
  <%= @fuel_type.url %>
</p>

<%= link_to 'Back', fuel_types_path %>
<%= link_to 'Edit', edit_fuel_type_path(@fuel_type) %>