config/routes.rb
TermProject::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  root 'welcome#index'

  get 'stations/search(.:format)' => 'stations#search'

  resources :stations, :prices, :fuel_types, :station_fuel_types, :cities, :zip_codes

end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :station_fuel_type

  validates :station_fuel_type_id, presence: true
  validates :price, presence: true
  validates :time, presence: true 
end

app/models/prices.rb
class Prices < ActiveRecord::Base
  belongs_to :station_fuel_types

  has_one :station, through: :station_fuel_types
  has_one :fuel_type, through: :station_fuel_types
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def create
    @price = Price.new(price_params)

    if @price.save
      redirect_to @price
    else
      render 'new'
    end
  end

  def destroy
    @price = Price.find(params[:id])
    @price.destroy

    redirect_to prices_path
  end

  def edit
    @price = Price.find(params[:id])
  end

  def index
    @prices = Price.all
  end

  def new
    @price = Price.new
  end

  def show
    @price = Price.find(params[:id])
  end

  def update
    @price = Price.find(params[:id])

    if @price.update(params[:price].permit(:station_fuel_type_id, :price, :time))
      redirect_to @price
    else
      render 'edit'
    end
  end

  private
    def price_params
      params.require(:price).permit(:station_fuel_type_id, :price, :time)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/edit.html.erb
<h1>Editing Price</h1>
 
<%= form_for :price, url: price_path(@price), method: :patch do |f| %>
  <% if @price.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@price.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @price.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :station_fuel_type_id %><br>
    <%= f.text_field :station_fuel_type_id %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing Prices</h1>

<%= link_to 'New Price', new_price_path %> 
<table border="1">
  <tr>
    <th>Station Fuel Type Id</th>
    <th>Price</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @prices.each do |price| %>
    <tr>
      <td><%= price.station_fuel_type_id %></td>
      <td><%= price.price %></td>
      <td><%= price.time %></td>
      <td><%= link_to 'Show', price %></td>
      <td><%= link_to 'Edit', edit_price_path(price) %></td>
      <td><%= link_to 'Destroy', price_path(price),
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br />

<%= link_to 'Back', controller: "welcome" %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= form_for :price, url: prices_path do |f| %>
  <% if @price.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@price.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @price.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :station_fuel_type_id %><br>
    <%= f.text_field :station_fuel_type_id %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p>
  <strong>Station Fuel Type Id:</strong>
  <%= @price.station_fuel_type_id %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>
 
<p>
  <strong>Time:</strong>
  <%= @price.time %>
</p>

<%= link_to 'Back', prices_path %>
<%= link_to 'Edit', edit_price_path(@price) %>